### ISSUE TITLE
Email IOCs

### ISSUE THREAD

**Issue by shnoogie** [JohnnyWachter/intel#1]
Could you please add email IOCs?

**Comment by JohnnyWachter** [comment]
Email address parsing has been added.  Email is validated both against RFC 822, and known-valid domain names; this is because per RFC, 'johnny-wachter' is considered a valid email address, though we know that this is clearly not addressable on the internet.  I validate that the following conditions are met:

* Conforms to RFC 822
* Contains an '@' symbol
* Ends with a Valid Domain Name (using my Domains class for this)
